// Compiles the pool (and the test token) with solc 0.8.24 for evm "paris".
// Arc rejects PUSH0 in some verifiers, so the target stays below shanghai.
//
//   node contracts/build.mjs
//
// Writes lib/market/lendingPoolArtifact.ts for the site and
// contracts/out/*.json for the tests.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import solc from 'solc';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sources = {
  'src/LendingPool.sol': readFileSync(join(root, 'contracts/src/LendingPool.sol'), 'utf8'),
  'src/IsolatedMarket.sol': readFileSync(join(root, 'contracts/src/IsolatedMarket.sol'), 'utf8'),
  'src/MarketFactory.sol': readFileSync(join(root, 'contracts/src/MarketFactory.sol'), 'utf8'),
  'src/LeverageRouter.sol': readFileSync(join(root, 'contracts/src/LeverageRouter.sol'), 'utf8'),
  'src/PoolQuote.sol': readFileSync(join(root, 'contracts/src/PoolQuote.sol'), 'utf8'),
  'src/FlashHelper.sol': readFileSync(join(root, 'contracts/src/FlashHelper.sol'), 'utf8'),
  'src/NftEscrow.sol': readFileSync(join(root, 'contracts/src/NftEscrow.sol'), 'utf8'),
  'src/TestNft.sol': readFileSync(join(root, 'contracts/src/TestNft.sol'), 'utf8'),
  'src/StakeVault.sol': readFileSync(join(root, 'contracts/src/StakeVault.sol'), 'utf8'),
  'src/Ballot.sol': readFileSync(join(root, 'contracts/src/Ballot.sol'), 'utf8'),
  'src/PoolBuyer.sol': readFileSync(join(root, 'contracts/src/PoolBuyer.sol'), 'utf8'),
  'src/V4Market.sol': readFileSync(join(root, 'contracts/src/V4Market.sol'), 'utf8'),
  'src/DeveloperInbox.sol': readFileSync(join(root, 'contracts/src/DeveloperInbox.sol'), 'utf8'),
  'test/MockNft.sol': readFileSync(join(root, 'contracts/test/MockNft.sol'), 'utf8'),
  'test/MockToken.sol': readFileSync(join(root, 'contracts/test/MockToken.sol'), 'utf8'),
  'test/MockV2Pair.sol': readFileSync(join(root, 'contracts/test/MockV2Pair.sol'), 'utf8'),
  'test/MockOracle.sol': readFileSync(join(root, 'contracts/test/MockOracle.sol'), 'utf8'),
  'test/MockSwap.sol': readFileSync(join(root, 'contracts/test/MockSwap.sol'), 'utf8'),
  'test/MockFlash.sol': readFileSync(join(root, 'contracts/test/MockFlash.sol'), 'utf8'),
};

const input = {
  language: 'Solidity',
  sources: Object.fromEntries(Object.entries(sources).map(([k, content]) => [k, { content }])),
  settings: {
    evmVersion: 'paris',
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (output.errors ?? []).filter((e) => e.severity === 'error');
for (const e of output.errors ?? []) console.error(e.formattedMessage);
if (errors.length) process.exit(1);

mkdirSync(join(root, 'contracts/out'), { recursive: true });
const pick = (file, name) => {
  const c = output.contracts[file][name];
  return { abi: c.abi, bytecode: `0x${c.evm.bytecode.object}` };
};

const pool = pick('src/LendingPool.sol', 'LendingPool');
const token = pick('test/MockToken.sol', 'MockToken');
writeFileSync(join(root, 'contracts/out/LendingPool.json'), JSON.stringify(pool, null, 2));
writeFileSync(join(root, 'contracts/out/MockToken.json'), JSON.stringify(token, null, 2));
writeFileSync(
  join(root, 'contracts/out/MockV2Pair.json'),
  JSON.stringify(pick('test/MockV2Pair.sol', 'MockV2Pair'), null, 2),
);
for (const [file, name] of [
  ['src/IsolatedMarket.sol', 'IsolatedMarket'],
  ['src/MarketFactory.sol', 'MarketFactory'],
  ['src/LeverageRouter.sol', 'LeverageRouter'],
  ['src/PoolQuote.sol', 'PoolQuote'],
  ['src/FlashHelper.sol', 'FlashHelper'],
  ['src/NftEscrow.sol', 'NftEscrow'],
  ['src/StakeVault.sol', 'StakeVault'],
  ['src/StakeVault.sol', 'BagToken'],
  ['src/Ballot.sol', 'Ballot'],
  ['src/PoolBuyer.sol', 'PoolBuyer'],
  ['src/V4Market.sol', 'V4Market'],
  ['test/MockNft.sol', 'MockNft'],
  ['test/MockOracle.sol', 'MockOracle'],
  ['test/MockSwap.sol', 'MockSwap'],
  ['test/MockFlash.sol', 'MockFlash'],
]) {
  writeFileSync(join(root, `contracts/out/${name}.json`), JSON.stringify(pick(file, name), null, 2));
}

writeFileSync(
  join(root, 'lib/market/lendingPoolArtifact.ts'),
  `// Generated by contracts/build.mjs from contracts/src/LendingPool.sol. Do not edit.\n` +
    `export const lendingPoolArtifactAbi = ${JSON.stringify(pool.abi, null, 2)} as const;\n\n` +
    `export const lendingPoolBytecode = '${pool.bytecode}' as const;\n`,
);

const isolated = ['IsolatedMarket', 'MarketFactory', 'LeverageRouter', 'PoolQuote', 'FlashHelper', 'NftEscrow', 'StakeVault', 'Ballot', 'PoolBuyer'].map(
  (name) => pick(`src/${name}.sol`, name),
);
const [isolatedMarket, marketFactory, leverageRouter, poolQuote, flashHelper, nftEscrow, stakeVault, ballot, poolBuyer] = isolated;
writeFileSync(
  join(root, 'lib/market/isolatedArtifact.ts'),
  `// Generated by contracts/build.mjs. Do not edit.\n` +
    `export const isolatedMarketAbi = ${JSON.stringify(isolatedMarket.abi, null, 2)} as const;\n` +
    `export const isolatedMarketBytecode = '${isolatedMarket.bytecode}' as const;\n` +
    `export const marketFactoryAbi = ${JSON.stringify(marketFactory.abi, null, 2)} as const;\n` +
    `export const marketFactoryBytecode = '${marketFactory.bytecode}' as const;\n` +
    `export const leverageRouterAbi = ${JSON.stringify(leverageRouter.abi, null, 2)} as const;\n` +
    `export const leverageRouterBytecode = '${leverageRouter.bytecode}' as const;\n` +
    `export const poolQuoteAbi = ${JSON.stringify(poolQuote.abi, null, 2)} as const;\n` +
    `export const poolQuoteBytecode = '${poolQuote.bytecode}' as const;\n` +
    `export const flashHelperAbi = ${JSON.stringify(flashHelper.abi, null, 2)} as const;\n` +
    `export const flashHelperBytecode = '${flashHelper.bytecode}' as const;\n` +
    `export const nftEscrowAbi = ${JSON.stringify(nftEscrow.abi, null, 2)} as const;\n` +
    `export const nftEscrowBytecode = '${nftEscrow.bytecode}' as const;\n` +
    `export const stakeVaultAbi = ${JSON.stringify(stakeVault.abi, null, 2)} as const;\n` +
    `export const stakeVaultBytecode = '${stakeVault.bytecode}' as const;\n` +
    `export const ballotAbi = ${JSON.stringify(ballot.abi, null, 2)} as const;\n` +
    `export const ballotBytecode = '${ballot.bytecode}' as const;\n` +
    `export const poolBuyerAbi = ${JSON.stringify(poolBuyer.abi, null, 2)} as const;\n` +
    `export const poolBuyerBytecode = '${poolBuyer.bytecode}' as const;\n`,
);

const testNft = pick('src/TestNft.sol', 'TestNft');
writeFileSync(join(root, 'contracts/out/TestNft.json'), JSON.stringify(testNft, null, 2));
writeFileSync(
  join(root, 'lib/market/testNftArtifact.ts'),
  `// Generated by contracts/build.mjs. Do not edit.\n` +
    `export const testNftAbi = ${JSON.stringify(testNft.abi, null, 2)} as const;\n` +
    `export const testNftBytecode = '${testNft.bytecode}' as const;\n`,
);

const v4Market = pick('src/V4Market.sol', 'V4Market');
writeFileSync(
  join(root, 'lib/market/v4MarketArtifact.ts'),
  `// Generated by contracts/build.mjs. Do not edit.\n` +
    `export const v4MarketAbi = ${JSON.stringify(v4Market.abi, null, 2)} as const;\n` +
    `export const v4MarketBytecode = '${v4Market.bytecode}' as const;\n`,
);

const developerInbox = pick('src/DeveloperInbox.sol', 'DeveloperInbox');
writeFileSync(join(root, 'contracts/out/DeveloperInbox.json'), JSON.stringify(developerInbox, null, 2));
writeFileSync(
  join(root, 'lib/market/developerInboxArtifact.ts'),
  `// Generated by contracts/build.mjs. Do not edit.\n` +
    `export const developerInboxAbi = ${JSON.stringify(developerInbox.abi, null, 2)} as const;\n` +
    `export const developerInboxBytecode = '${developerInbox.bytecode}' as const;\n`,
);

console.log(`LendingPool ${(pool.bytecode.length - 2) / 2} bytes, MockToken ${(token.bytecode.length - 2) / 2} bytes`);
